---
# yaml-language-server: $schema=https://raw.githubusercontent.com/goss-org/goss/master/docs/schema.yaml
process:
  # 15 character limit
  prometheus-dnss:
    running: true

port:
  tcp6:9204:
    listening: true

http:
  http://localhost:9204/metrics:
    status: 200
