# This workflow runs on certain conditions to check for and potentially
# delete container images from the GHCR which no longer have an associated
# code branch.
# Requires a PAT with the correct scope set in the secrets.
#
# This workflow will not trigger runs on forked repos.

name: Container Cleanup

on:
  pull_request:
    types:
      - "closed"
  push:
    paths:
      - ".github/workflows/container-cleanup.yaml"
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:

permissions:
  packages: write

jobs:
  cleanup:
    name: Cleanup Untagged Images
    runs-on: ubuntu-latest
    env:
      # Requires a personal access token with the OAuth scope delete:packages
      TOKEN: ${{ secrets.PACKAGE_DELETE_TOKEN }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ env.TOKEN }}

      - name: Delete all containers from package without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@v5
        with:
          token: ${{ env.TOKEN }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          untagged_only: true
          owner_type: user
          except_untagged_multiplatform: true
